project_id = "gedgcagidpheugikoyim"

[functions.send-auto-reply]
verify_jwt = false

[functions.secure-forms]
verify_jwt = false

[functions.secure-storage]
verify_jwt = false

[functions.secure-email]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.process-content]
verify_jwt = false

[functions.translate-dictionary]
verify_jwt = false

[functions.translate-term]
verify_jwt = false

[functions.test-openai-connection]
verify_jwt = false

[functions.ai-lexicon-generator]
verify_jwt = false

[functions.ai-lexicon-generator-with-retry]
verify_jwt = false

[functions.world-reference-seeder]
verify_jwt = false

[functions.auto-translate-term]
verify_jwt = false

[functions.bulk-import-lexicon]
verify_jwt = false

[functions.on-demand-lexicon]
verify_jwt = false

[functions.bulk-lexicon-seeder]
verify_jwt = false

[functions.send-application-emails]
verify_jwt = false

[functions.send-teacher-application-emails]
verify_jwt = false

[functions.send-secure-emails]
verify_jwt = false

[functions.dynamic-translate]
verify_jwt = false
