project_id = "gedgcagidpheugikoyim"

[functions.send-auto-reply]
verify_jwt = false

[functions.secure-forms]
verify_jwt = false

[functions.secure-storage]
verify_jwt = false

[functions.secure-email]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
