project_id = "gedgcagidpheugikoyim"

[functions.send-auto-reply]
verify_jwt = false

[functions.secure-forms]
verify_jwt = false

[functions.secure-storage]
verify_jwt = false

[functions.secure-email]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.process-content]
verify_jwt = false

[functions.translate-dictionary]
verify_jwt = false

[functions.translate-term]
verify_jwt = false
