-- First, let's see what categories exist and update them
UPDATE dictionary SET category = 'Management' WHERE category NOT IN ('Management', 'Leadership', 'Psychology', 'Finance', 'Digital Life', 'Study Skills', 'Communication', 'Sociology', 'Philosophy', 'Ethics');

-- Now add the constraint with all valid categories
ALTER TABLE dictionary ADD CONSTRAINT dictionary_category_check 
CHECK (category IN ('Management', 'Leadership', 'Psychology', 'Finance', 'Digital Life', 'Study Skills', 'Communication', 'Sociology', 'Philosophy', 'Ethics', 'Entrepreneurship', 'Economics'));

-- Insert some sample enhanced terms
INSERT INTO dictionary (term, slug, short_def, long_def, category, discipline_tags, examples, synonyms, phonetic_en, complexity_level, difficulty_score, age_appropriateness, status) VALUES
('Risk Assessment', 'risk-assessment', 'Evaluating potential threats and opportunities', 'The systematic process of identifying, analyzing, and evaluating potential risks that could affect an organization or project. Risk assessment helps leaders make informed decisions by understanding what could go wrong and how likely it is to happen.', 'Management', ARRAY['Management', 'Strategy', 'Decision Making'], ARRAY['The risk assessment revealed potential cybersecurity vulnerabilities'], ARRAY['Risk Analysis', 'Threat Evaluation'], 'rɪsk ə-ˈses-mənt', 'intermediate', 6, 'teenager', 'published'),
('Team Building', 'team-building', 'Creating strong, collaborative groups', 'The process of turning a group of individuals into a cohesive team that works together effectively. Team building involves developing trust, communication, and shared goals among team members.', 'Leadership', ARRAY['Leadership', 'Management', 'Psychology'], ARRAY['Team building activities helped improve collaboration in the workplace'], ARRAY['Team Development', 'Group Dynamics'], 'tim ˈbɪl-dɪŋ', 'beginner', 4, 'teenager', 'published'),
('Problem Solving', 'problem-solving', 'Finding solutions to challenges', 'The process of identifying problems, analyzing their causes, and implementing effective solutions. Strong problem-solving skills help leaders navigate complex situations and make decisions under pressure.', 'Management', ARRAY['Management', 'Critical Thinking', 'Decision Making'], ARRAY['Her problem-solving approach helped resolve the customer service issues'], ARRAY['Solution Finding', 'Issue Resolution'], 'ˈprɑb-ləm ˈsɑlv-ɪŋ', 'beginner', 3, 'teenager', 'published'),
('Conflict Resolution', 'conflict-resolution', 'Resolving disagreements constructively', 'The process of addressing and resolving disputes between individuals or groups in a peaceful and productive manner. Effective conflict resolution maintains relationships while finding solutions that work for everyone involved.', 'Communication', ARRAY['Communication', 'Leadership', 'Psychology'], ARRAY['Conflict resolution skills helped mediate the team dispute'], ARRAY['Dispute Resolution', 'Mediation'], 'ˈkɑn-flɪkt ˌrez-ə-ˈlu-ʃən', 'intermediate', 5, 'teenager', 'published'),
('Project Management', 'project-management', 'Planning and executing projects successfully', 'The application of knowledge, skills, tools, and techniques to project activities to meet project requirements. Project management involves initiating, planning, executing, monitoring, and closing projects effectively.', 'Management', ARRAY['Management', 'Organization', 'Leadership'], ARRAY['Good project management ensured the event was completed on time and budget'], ARRAY['Project Planning', 'Project Coordination'], 'ˈprɑdʒ-ekt ˈmæn-ɪdʒ-mənt', 'intermediate', 6, 'teenager', 'published')
ON CONFLICT (slug) DO NOTHING;