-- Seed TMA Lexicon with comprehensive management and leadership terms
INSERT INTO dictionary (
    slug, term, short_def, long_def, category, discipline_tags, 
    status, verification_status, created_at, updated_at
) VALUES
    ('accountability', 'Accountability', 'The obligation to take responsibility for one''s actions and decisions, especially in leadership roles.', 'The obligation to take responsibility for one''s actions and decisions, especially in leadership roles. For teenagers learning management skills, accountability means owning up to both successes and mistakes, learning from them, and being reliable in commitments.', 'Management', ARRAY['accountability', 'responsibility', 'ethics'], 'published', 'verified', now(), now()),
    ('adaptability', 'Adaptability', 'The ability to adjust to new conditions and challenges, crucial for modern leadership.', 'The ability to adjust to new conditions and challenges, crucial for modern leadership. In today''s fast-changing world, teenage leaders must be flexible and open to learning new ways of doing things when circumstances change.', 'Leadership', ARRAY['flexibility', 'change management', 'resilience'], 'published', 'verified', now(), now()),
    ('assertiveness', 'Assertiveness', 'Confidently expressing one''s opinions and needs while respecting others.', 'Confidently expressing one''s opinions and needs while respecting others. This involves standing up for yourself and your beliefs without being aggressive or disrespectful to others. It''s about finding the balance between being passive and being aggressive.', 'Psychology', ARRAY['confidence', 'communication', 'self-advocacy'], 'published', 'verified', now(), now()),
    ('brainstorming', 'Brainstorming', 'A creative problem-solving technique where individuals generate ideas freely.', 'A creative problem-solving technique where individuals or teams generate ideas freely without immediate judgment or criticism. The goal is to produce as many creative solutions as possible before evaluating their feasibility.', 'Management', ARRAY['creativity', 'problem solving', 'teamwork'], 'published', 'verified', now(), now()),
    ('collaboration', 'Collaboration', 'Working together effectively with others to achieve common goals.', 'Working together effectively with others to achieve common goals. It involves sharing responsibilities, communicating openly, and combining different skills and perspectives to create better outcomes than what could be achieved individually.', 'Leadership', ARRAY['teamwork', 'cooperation', 'partnership'], 'published', 'verified', now(), now()),
    ('decision-making', 'Decision Making', 'The process of choosing between alternatives to solve problems or achieve goals.', 'The process of choosing between alternatives to solve problems or achieve goals. Effective decision-making involves gathering information, weighing options, considering consequences, and choosing the best course of action based on available evidence.', 'Management', ARRAY['analysis', 'judgment', 'problem solving'], 'published', 'verified', now(), now()),
    ('delegation', 'Delegation', 'Assigning tasks and responsibilities to others while maintaining accountability.', 'Assigning tasks and responsibilities to others while maintaining overall accountability for results. Good delegation involves choosing the right person for the task, providing clear instructions, and supporting them while allowing autonomy.', 'Leadership', ARRAY['task management', 'trust', 'empowerment'], 'published', 'verified', now(), now()),
    ('emotional-intelligence', 'Emotional Intelligence', 'The ability to understand and manage your own emotions and those of others.', 'The ability to understand and manage your own emotions and those of others. It includes self-awareness, self-regulation, empathy, and social skills. High emotional intelligence helps in building better relationships and making more thoughtful decisions.', 'Psychology', ARRAY['self-awareness', 'empathy', 'social skills'], 'published', 'verified', now(), now()),
    ('feedback', 'Feedback', 'Information given to help improve performance or behavior.', 'Information given to help improve performance or behavior. Constructive feedback is specific, timely, and focused on actions rather than personality. It should help the recipient understand what they did well and what they can improve.', 'Management', ARRAY['improvement', 'communication', 'development'], 'published', 'verified', now(), now()),
    ('goal-setting', 'Goal Setting', 'The process of establishing specific, measurable, achievable, relevant, and time-bound objectives.', 'The process of establishing specific, measurable, achievable, relevant, and time-bound objectives (SMART goals). Effective goal-setting provides direction, motivation, and a way to measure progress toward desired outcomes.', 'Management', ARRAY['planning', 'objectives', 'SMART goals'], 'published', 'verified', now(), now()),
    ('innovation', 'Innovation', 'The introduction of new ideas, methods, or products to create value.', 'The introduction of new ideas, methods, or products to create value. Innovation involves creative thinking, experimentation, and the willingness to try new approaches to solve problems or improve existing solutions.', 'Leadership', ARRAY['creativity', 'change', 'improvement'], 'published', 'verified', now(), now()),
    ('integrity', 'Integrity', 'Adherence to moral and ethical principles, being honest and having strong moral values.', 'Adherence to moral and ethical principles, being honest and having strong moral values. Integrity means doing the right thing even when no one is watching and being consistent in your values and actions.', 'Psychology', ARRAY['ethics', 'honesty', 'values'], 'published', 'verified', now(), now()),
    ('mentorship', 'Mentorship', 'A relationship where an experienced person guides and supports someone less experienced.', 'A relationship where an experienced person guides and supports someone less experienced. Mentorship involves sharing knowledge, providing advice, and helping mentees develop their skills and reach their potential.', 'Leadership', ARRAY['guidance', 'development', 'support'], 'published', 'verified', now(), now()),
    ('networking', 'Networking', 'Building and maintaining professional relationships for mutual benefit.', 'Building and maintaining professional relationships for mutual benefit. Effective networking involves genuine interest in others, offering help when possible, and maintaining connections over time.', 'Management', ARRAY['relationships', 'connections', 'professional development'], 'published', 'verified', now(), now()),
    ('organization', 'Organization', 'The systematic arrangement of tasks, resources, and people to achieve objectives efficiently.', 'The systematic arrangement of tasks, resources, and people to achieve objectives efficiently. Good organization involves planning, structuring activities logically, and ensuring everyone knows their roles and responsibilities.', 'Management', ARRAY['structure', 'efficiency', 'systems'], 'published', 'verified', now(), now()),
    ('prioritization', 'Prioritization', 'Determining the order of importance of tasks or goals to maximize effectiveness.', 'Determining the order of importance of tasks or goals to maximize effectiveness. Prioritization helps focus energy and resources on what matters most, ensuring important tasks are completed first.', 'Management', ARRAY['time management', 'efficiency', 'focus'], 'published', 'verified', now(), now()),
    ('resilience', 'Resilience', 'The ability to recover quickly from difficulties and adapt to challenging situations.', 'The ability to recover quickly from difficulties and adapt to challenging situations. Resilience involves mental toughness, optimism, and the capacity to learn and grow from setbacks rather than being defeated by them.', 'Psychology', ARRAY['strength', 'recovery', 'perseverance'], 'published', 'verified', now(), now()),
    ('strategy', 'Strategy', 'A plan of action designed to achieve long-term goals or overall aims.', 'A plan of action designed to achieve long-term goals or overall aims. Strategic thinking involves analyzing the current situation, envisioning the desired future, and planning the steps needed to bridge the gap.', 'Management', ARRAY['planning', 'vision', 'direction'], 'published', 'verified', now(), now()),
    ('team-building', 'Team Building', 'Activities and processes designed to improve team performance and relationships.', 'Activities and processes designed to improve team performance and relationships. Team building focuses on creating trust, improving communication, and helping team members work together more effectively toward common goals.', 'Leadership', ARRAY['teamwork', 'collaboration', 'group dynamics'], 'published', 'verified', now(), now()),
    ('time-management', 'Time Management', 'The ability to use time effectively and efficiently to accomplish tasks and goals.', 'The ability to use time effectively and efficiently to accomplish tasks and goals. Good time management involves planning, setting priorities, avoiding distractions, and using techniques to maximize productivity while maintaining work-life balance.', 'Management', ARRAY['productivity', 'scheduling', 'efficiency'], 'published', 'verified', now(), now())
ON CONFLICT (slug) DO NOTHING;