-- Fix dictionary category constraint and add entrepreneurship
ALTER TABLE dictionary DROP CONSTRAINT IF EXISTS dictionary_category_check;

-- Add new category constraint including Entrepreneurship
ALTER TABLE dictionary ADD CONSTRAINT dictionary_category_check 
CHECK (category IN ('Management', 'Leadership', 'Psychology', 'Finance', 'Digital Life', 'Study Skills', 'Communication', 'Sociology', 'Philosophy', 'Ethics', 'Entrepreneurship', 'Economics'));

-- Now insert the terms
INSERT INTO dictionary (term, slug, short_def, long_def, category, discipline_tags, examples, synonyms, phonetic_en, complexity_level, difficulty_score, age_appropriateness, status) VALUES
('Accountability', 'accountability', 'Taking responsibility for actions and results', 'The practice of taking ownership of decisions, actions, and their consequences. In leadership, accountability means being answerable for outcomes and learning from both successes and failures.', 'Leadership', ARRAY['Leadership', 'Ethics', 'Management'], ARRAY['The team leader showed accountability by admitting the mistake and proposing solutions'], ARRAY['Responsibility', 'Ownership'], 'ə-ˈkaʊn-tə-ˈbɪl-ə-ti', 'beginner', 3, 'teenager', 'published'),
('Strategic Planning', 'strategic-planning', 'Long-term planning to achieve organizational goals', 'The process of defining an organization''s strategy and making decisions on allocating resources to pursue this strategy. Strategic planning involves setting goals and determining actions to achieve them.', 'Management', ARRAY['Management', 'Strategy', 'Planning'], ARRAY['Strategic planning helped the company navigate market changes successfully'], ARRAY['Long-term Planning', 'Strategic Management'], 'strə-ˈti-dʒɪk ˈplæn-ɪŋ', 'intermediate', 6, 'teenager', 'published'),
('Innovation', 'innovation', 'The introduction of new ideas, methods, or products', 'The process of creating and implementing new ideas, products, services, or processes that provide value. Innovation drives progress by solving problems in novel ways.', 'Entrepreneurship', ARRAY['Entrepreneurship', 'Creativity', 'Technology'], ARRAY['The company''s innovation in renewable energy revolutionized the industry'], ARRAY['Creativity', 'Invention'], 'ˌɪn-ə-ˈveɪ-ʃən', 'intermediate', 5, 'teenager', 'published'),
('Emotional Intelligence', 'emotional-intelligence', 'The ability to understand and manage emotions', 'The capacity to recognize, understand, and manage our own emotions while effectively handling relationships with others. High emotional intelligence helps leaders connect with people.', 'Psychology', ARRAY['Psychology', 'Leadership', 'Communication'], ARRAY['Her emotional intelligence helped her mediate conflicts between team members'], ARRAY['EQ', 'Social Intelligence'], 'ɪ-ˈmoʊ-ʃən-əl ɪn-ˈtel-ə-dʒəns', 'intermediate', 6, 'teenager', 'published'),
('Digital Literacy', 'digital-literacy', 'The ability to use digital technology effectively', 'The knowledge, skills, and behaviors involved in using digital devices and platforms. Digital literacy includes understanding how to find, evaluate, and communicate information online.', 'Digital Life', ARRAY['Digital Life', 'Technology', 'Education'], ARRAY['Digital literacy helps students research effectively and avoid misinformation'], ARRAY['Tech Skills', 'Computer Literacy'], 'ˈdɪdʒ-ə-təl ˈlɪt-ər-ə-si', 'intermediate', 5, 'teenager', 'published'),
('Risk Management', 'risk-management', 'Identifying and managing potential threats', 'The process of identifying, assessing, and controlling threats to an organization''s capital and earnings. Effective risk management helps entrepreneurs make informed decisions.', 'Entrepreneurship', ARRAY['Entrepreneurship', 'Management', 'Finance'], ARRAY['Good risk management helped the startup navigate market uncertainties'], ARRAY['Risk Assessment', 'Risk Control'], 'rɪsk ˈmæn-ɪdʒ-mənt', 'advanced', 7, 'teenager', 'published'),
('Communication Skills', 'communication-skills', 'The ability to convey information effectively', 'The ability to share information, ideas, and feelings clearly and effectively through various methods including speaking, writing, and body language. Strong communication skills are essential for leadership.', 'Communication', ARRAY['Communication', 'Leadership', 'Social Skills'], ARRAY['Strong communication skills helped her lead the project team successfully'], ARRAY['Communication Abilities', 'Interpersonal Skills'], 'kə-ˌmyu-nə-ˈkeɪ-ʃən skɪlz', 'beginner', 4, 'teenager', 'published'),
('Time Management', 'time-management', 'The ability to use time effectively and efficiently', 'The process of organizing and planning how to divide your time between specific activities. Good time management enables you to accomplish more in a shorter period of time.', 'Management', ARRAY['Management', 'Productivity', 'Personal Development'], ARRAY['Effective time management helped students balance academics and extracurriculars'], ARRAY['Time Planning', 'Schedule Management'], 'taɪm ˈmæn-ɪdʒ-mənt', 'beginner', 3, 'teenager', 'published')
ON CONFLICT (slug) DO NOTHING;